### ISSUE TITLE
configuring https for magento

### ISSUE THREAD

**Issue by charidimos** [alexcheng1982/docker-magento2#27]
Hello,

I successfully installed magento2 with docker but was unable to setup https://local.magento. 
I tried to expose and publish port 443 with in the yml file:
```
version: '3.0'
services:
  web:
    image: alexcheng/magento2
    expose: 
      - "443"
    ports:
      - "80:80"
      - "443:444"
    links:
      - db
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  db-data: 
```
hoever, without any success. During installation, I choose https for storefront. 
Any ideas?

Thanks a lot in advance
