### ISSUE TITLE
Where is the data...?

### ISSUE THREAD

**Issue by Zyles** [alexcheng1982/docker-magento2#41]
I installed, I can access phpmyadmin and the db is there etc, but where is the code base?

```
$ sudo ls /var/www
ls: cannot access '/var/www': No such file or directory
```

My docker-compose.yml:
```
services:
  web:
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - env
    volumes:
      - /home/magento-data:/var/www/html
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data:
  magento-data:
```

`$ sudo ls /home/magento-data/`

empty
