### ISSUE TITLE
once i docker-compose down i lose all my settings 

### ISSUE THREAD

**Issue by TheSearcher** [alexcheng1982/docker-magento2#52]
i was able to spin a magento2 version with docker-compose up - 

however, once i docker-compose down i lose everything. 

is this how its set up to be or did i do something wrong.

thank you

**Comment by tomhrtly** [comment]
Try `docker-compose stop` instead.

**Comment by krskibin** [comment]
Is there any other solution for this? Maybe adding extra volume for Magento host data will solve the problem.

**Comment by osmansafak** [comment]
You must add volumes to the web service.

Edit the docker-compose.yml file as follows.

```
version: "3.0"
services:
  web:
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - web-file:/var/www
    env_file:
      - env
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data:
  web-file:
```

**Comment by krskibin** [comment]
Unfortunately @osmansafak, Your solution doesn't work.

**Comment by krskibin** [comment]
Unfortunetly, @osmansafak doesn't work. With your docker-compose config I can't even import data running install-sampledata command. It shows me some erros with authentication and so on :disappointed:.

**Comment by Gorynych** [comment]
I got the same problem.

And it's very strange. Using volumes actually intends to not have it, but... ((

**Comment by TheSearcher** [comment]
@osmansafak  hi. can you raise this question/issue on [https://magento.stackexchange.com/](url) and i will show you how to fix the error

**Comment by philologos** [comment]
I had a similar problem.

After running `docker-compose up -d` and `docker exec -it <container-id> install-magento` everything worked fine. As soon as I ran `docker-compose down` and started to re-run the containers, a database error occured (could not find table). I did solve it by adapting the db volume destination from `db-data:/var/lib/mysql/data` to `db-data:/var/lib/mysql` and adding `external: true` to both named volumes. Therefore I had to create them before running `docker-compose up -d` with the commands `docker volume create --name=magento-data` and `docker volume create --name=db-data`. I am using `external: true` mainly since I had some issues in the past whilst referencing named volumes when project names changed, it might be not critical to solve the issue above. For the sake of completeness, you find my `docker-compose.yml` below:

```
version: '3'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    volumes: 
      - magento-data:/var/www/html  
    env_file:
      - env
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  magento-data:
    external: true
  db-data:
    external: true
```

Maybe this helps anybody. If this is a common problem it might worth a pull request.
