### ISSUE TITLE
Wrong PhpMyAdmin port in README.md

### ISSUE THREAD

**Issue by techiedesu** [alexcheng1982/docker-magento2#9]
Wrong PhpMyAdmin port in README.md. 

docker-compose.yml
```
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
```
README.md
```
### Database

...
The default URL for phpMyAdmin is `http://localhost:8085`. 
Use MySQL username and password to log in.
...
```
